### ISSUE TITLE
Bug: Calorie Data deleted after editing weight

### ISSUE THREAD

**Issue by junhui-phoon** [AY2021S1-CS2103T-W11-3/tp#90]
Found a bug during a random test:
Both calories in and out reset to 0 after entering edit command.

Steps to reproduce:
1. Edit an existing record with both calorie values are not 0 with this command: edit INDEX w/WEIGHT
2. Observe in the UI that both calories values change to 0 after execution.
3. Storage file is also overwritten.

**Comment by wayne987** [comment]
I think cos the edit create a new day object without copying over the claroieManager field
